version: "3"

x-common-env: &common-env
  INFLUXDB_URL: http://influxdb:8086
  INFLUXDB_TOKEN: my-secret-token
  INFLUXDB_ORG: my-org
  INFLUXDB_BUCKET: logs
  LOG_LEVEL: INFO
  REDIS_URL: redis://redis:6379/0

services:
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
      - ./error_reports:/app/error_reports
    depends_on:
      - redis
      - influxdb
    environment:
      <<: *common-env

  celery_worker_1:
    build: .
    command: celery -A main.celery_app worker --loglevel=info --hostname=worker1@%h
    volumes:
      - ./logs:/logs
      - ./error_reports:/error_reports
    depends_on:
      - redis
      - influxdb
    environment:
      <<: *common-env

  celery_worker_2:
    build: .
    command: celery -A main.celery_app worker --loglevel=info --hostname=worker2@%h
    volumes:
      - ./logs:/logs
      - ./error_reports:/error_reports
    depends_on:
      - redis
      - influxdb
    environment:
      <<: *common-env

  redis:
    image: redis:alpine

  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=logs
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-secret-token

volumes:
  influxdb_data:
